### PR TITLE
Add temporary class command

### PR DESCRIPTION
**Pull request by jamesyeap**
This pull-request adds a new command allowing a user to add a temporary class using the following command:
`addlesson -n <LESSON_NAME> -s <SUBJECT> -a <ADDRESS_OF_LESSON> -d <DATE_OF_LESSON> -t <STARTING_TIME> -h <DURATION_OF_LESSON_IN_HOURS> -m <DURATION_OF_LESSON_IN_MINUTES>`

example of usage:
- To add a non-recurring lesson with the following attributes:
   - name: Trial lesson for Henry
   - subject: Biology
   - where the lesson is conducted: Blk 11 Ang Mo Kio Street 74, # 11-04
   - on date: 27 February 2022
   - starting at: 6pm
   - duration: 1 hour and 50 minutes
- we input the following command:
   - `addlesson -n Trial lesson for Henry -s Biology -a Blk 11 Ang Mo Kio Street 74, #11-04 -d 27-02-2022 -t 18:00 -h 1 -m 50`

It also adds some test-cases for the Lesson class and the associated classes associated with it.

### CODE REVIEW

**Comment by jamesyeap** [comment]
Fixes #11

**Comment by jamesyeap** [comment]
Updates #56

**Comment by jamesyeap** [comment]
Fixes #65

**Review by Ryan-L98 — APPROVED** [review]
LGTM~

**Pull request merged**
